apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-flex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-flex
  template:
    metadata:
      labels:
        app: custom-flex
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: custom-flex
        image: ghcr.io/thomasplantain/custom-flex:1.0.7
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
